import Tkinter
from Tkinter import *  
from Tkinter import Label, Button, END
from Tix import Tk, Control, ComboBox 
from tkMessageBox import showinfo, showwarning, showerror 


root = Tkinter.Tk()
root.geometry('800x600')
root.title("Schedule")

fm1 = Frame(root)
Label(fm1, text='MonthlySchedule').pack(side=LEFT, anchor=W, ipadx=6)
Label(fm1, text='ASU1').pack(side=LEFT, anchor=W, ipadx=36)
Label(fm1, text='ASU2').pack(side=LEFT, anchor=W, ipadx=36)
Label(fm1, text='ASU3').pack(side=LEFT, anchor=W, ipadx=36)
Label(fm1, text='ASU4').pack(side=LEFT, anchor=W, ipadx=36)
fm1.pack(side=TOP, fill=X)

fm2 = Frame(root)
Label(fm2, text='GOX').pack(side=LEFT, anchor=W, ipadx=40)
t1 = Text(fm2, width=16, height=1)
t1.insert(INSERT, 'GOX')
t1.pack(side=LEFT, anchor=CENTER)
t2 = Text(fm2, width=15, height=1)
t2.insert(INSERT, 'GOX')
t2.pack(side=LEFT, anchor=CENTER)
t3 = Text(fm2, width=15, height=1)
t3.insert(INSERT, 'GOX')
t3.pack(side=LEFT, anchor=CENTER)
t4 = Text(fm2, width=15, height=1)
t4.insert(INSERT, 'GOX')
t4.pack(side=LEFT, anchor=CENTER)
fm2.pack(side=TOP, fill=X)

fm3 = Frame(root)
Label(fm3, text='LOX').pack(side=LEFT, anchor=W, ipadx=41)
t1 = Text(fm3, width=16, height=1)
t1.insert(INSERT, 'LOX')
t1.pack(side=LEFT, anchor=CENTER)
t2 = Text(fm3, width=15, height=1)
t2.insert(INSERT, 'LOX')
t2.pack(side=LEFT, anchor=CENTER)
t3 = Text(fm3, width=15, height=1)
t3.insert(INSERT, 'LOX')
t3.pack(side=LEFT, anchor=CENTER)
t4 = Text(fm3, width=15, height=1)
t4.insert(INSERT, 'LOX')
t4.pack(side=LEFT, anchor=CENTER)
fm3.pack(side=TOP, fill=X)

fm4 = Frame(root)
Label(fm4, text='GAN').pack(side=LEFT, anchor=W, ipadx=40)
t1 = Text(fm4, width=16, height=1)
t1.insert(INSERT, 'GAN')
t1.pack(side=LEFT, anchor=CENTER)
t2 = Text(fm4, width=15, height=1)
t2.insert(INSERT, 'GAN')
t2.pack(side=LEFT, anchor=CENTER)
t3 = Text(fm4, width=15, height=1)
t3.insert(INSERT, 'GAN')
t3.pack(side=LEFT, anchor=CENTER)
t4 = Text(fm4, width=15, height=1)
t4.insert(INSERT, 'GAN')
t4.pack(side=LEFT, anchor=CENTER)
fm4.pack(side=TOP, fill=X)

fm5 = Frame(root)
Label(fm5, text='LIN').pack(side=LEFT, anchor=W, ipadx=42)
t1 = Text(fm5, width=16, height=1)
t1.insert(INSERT, 'LIN')
t1.pack(side=LEFT, anchor=CENTER)
t2 = Text(fm5, width=15, height=1)
t2.insert(INSERT, 'LIN')
t2.pack(side=LEFT, anchor=CENTER)
t3 = Text(fm5, width=15, height=1)
t3.insert(INSERT, 'LIN')
t3.pack(side=LEFT, anchor=CENTER)
t4 = Text(fm5, width=15, height=1)
t4.insert(INSERT, 'LIN')
t4.pack(side=LEFT, anchor=CENTER)
fm5.pack(side=TOP, fill=X)

fm6 = Frame(root)
Label(fm6, text='GAR').pack(side=LEFT, anchor=W, ipadx=41)
t1 = Text(fm6, width=16, height=1)
t1.insert(INSERT, 'GAR')
t1.pack(side=LEFT, anchor=CENTER)
t2 = Text(fm6, width=15, height=1)
t2.insert(INSERT, 'GAR')
t2.pack(side=LEFT, anchor=CENTER)
t3 = Text(fm6, width=15, height=1)
t3.insert(INSERT, 'GAR')
t3.pack(side=LEFT, anchor=CENTER)
t4 = Text(fm6, width=15, height=1)
t4.insert(INSERT, 'GAR')
t4.pack(side=LEFT, anchor=CENTER)
fm6.pack(side=TOP, fill=X)

fm7 = Frame(root)
Label(fm7, text='LAR').pack(side=LEFT, anchor=W, ipadx=41)
t1 = Text(fm7, width=16, height=1)
t1.insert(INSERT, 'LAR')
t1.pack(side=LEFT, anchor=CENTER)
t2 = Text(fm7, width=15, height=1)
t2.insert(INSERT, 'LAR')
t2.pack(side=LEFT, anchor=CENTER)
t3 = Text(fm7, width=15, height=1)
t3.insert(INSERT, 'LAR')
t3.pack(side=LEFT, anchor=CENTER)
t4 = Text(fm7, width=15, height=1)
t4.insert(INSERT, 'LAR')
t4.pack(side=LEFT, anchor=CENTER)
fm7.pack(side=TOP, fill=X)

root.mainloop()

